### ISSUE TITLE
Detailed logging?

### ISSUE THREAD

**Issue by nmaxcom** [johnotander/postcss-shorthand-expand#1]
Hi!

Awesome plugin, thanks for the contribution. I have one tiny issue: when I run it, I have a few dozen lines where it says:

    postcss-shorthand-expand: /xxx.css:1134:3: postcss-shorthand-expand failed to expand a property
    postcss-shorthand-expand: /xxx.css:1144:3: postcss-shorthand-expand failed to expand a property
    postcss-shorthand-expand: /xxx.css:1194:3: postcss-shorthand-expand failed to expand a property
    ...

But xxx.css is in the src folder (and there I only use *.scss). But it isn't the final *.css also. So the error must be in some part of the gulp process. Bottom line: i never get to see which properties fails to expand.

**Comment by johnotander** [comment]
That's strange. Are you using sourcemaps by any chance? The errors are using PostCSS#result.warn API so it _should_ be mapping the error to the correct declaration.

Though, I should add more information to the error regardless, likely the selector and property where the error occurred. I should be able to get to that this weekend. I'll keep you posted.

**Comment by nmaxcom** [comment]
Yes I'm using sourcemaps too.

That'd be awesome, thanks.

**Comment by johnotander** [comment]
I've added a  more descriptive error message, it's published to npm as `postcss-shorthand-expand@1.0.1`. Let me know if you encounter any issues. Thanks!
